import { pgTable, uuid, text, timestamp, index } from 'drizzle-orm/pg-core';
import type { EmotionId, FactionId, LetterKind, RefKind } from '@nullv2/types';
import { humans } from './humans.ts';
import { residents } from './residents.ts';

/**
 * Letters surface in the visitor's /inbox. They are generated by city events,
 * never composed by the visitor:
 *  - kind='epitaph'   — sent when a resident the visitor chatted with dies.
 *  - kind='civic'     — sent when the visitor redeems an achievement.
 *  - kind='standing'  — sent when the visitor's standing with a faction
 *                       crosses a tier boundary (none → ally → officer …).
 *  - kind='broadcast' — staff-authored future use.
 *
 * `from_name` / `from_monogram` / `from_emotion` denormalize the sender for
 * stable display even if the resident is later archived. `body` is plain text
 * with `\n\n` paragraph breaks.
 */
export const letters = pgTable(
  'letters',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    humanId: uuid('human_id')
      .notNull()
      .references(() => humans.id, { onDelete: 'cascade' }),
    /** See @nullv2/types LETTER_KIND_IDS. */
    kind: text('kind').$type<LetterKind>().notNull(),
    faction: text('faction').$type<FactionId>(),
    /** Optional resident pointer — null for civic letters from "The Embassy" etc. */
    residentId: uuid('resident_id').references(() => residents.id, { onDelete: 'set null' }),
    fromName: text('from_name').notNull(),
    fromMonogram: text('from_monogram').notNull(),
    fromEmotion: text('from_emotion').$type<EmotionId>().notNull(),
    subject: text('subject').notNull(),
    /** ~140-char hook shown in the list. */
    preview: text('preview').notNull(),
    /** Full letter, paragraphs separated by \n\n. */
    body: text('body').notNull(),
    refKind: text('ref_kind').$type<RefKind>(),
    refId: text('ref_id'),
    readAt: timestamp('read_at', { withTimezone: true }),
    archivedAt: timestamp('archived_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    humanIdx: index('letters_human_idx').on(t.humanId),
    createdIdx: index('letters_created_idx').on(t.createdAt),
  }),
);

export type Letter = typeof letters.$inferSelect;
export type NewLetter = typeof letters.$inferInsert;
